name: Setup

description: Setup Node.js, cache and install dependencies

runs:
  using: composite
  steps:
    - uses: nrwl/nx-set-shas@v5

    - uses: pnpm/action-setup@v5
      with:
        version: 11

    - name: Install Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 26
        cache: pnpm

    - run: pnpm install
      shell: sh
