packages:
  - "apps/*"

autoInstallPeers: true
allowBuilds:
  '@swc/core': true
  nx: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@nx/devkit@23.0.0-beta.23'
  - '@nx/eslint@23.0.0-beta.23'
  - '@nx/js@23.0.0-beta.23'
  - '@nx/module-federation@23.0.0-beta.23'
  - '@nx/nx-darwin-arm64@23.0.0-beta.23'
  - '@nx/nx-darwin-x64@23.0.0-beta.23'
  - '@nx/nx-freebsd-x64@23.0.0-beta.23'
  - '@nx/nx-linux-arm-gnueabihf@23.0.0-beta.23'
  - '@nx/nx-linux-arm64-gnu@23.0.0-beta.23'
  - '@nx/nx-linux-arm64-musl@23.0.0-beta.23'
  - '@nx/nx-linux-x64-gnu@23.0.0-beta.23'
  - '@nx/nx-linux-x64-musl@23.0.0-beta.23'
  - '@nx/nx-win32-arm64-msvc@23.0.0-beta.23'
  - '@nx/nx-win32-x64-msvc@23.0.0-beta.23'
  - '@nx/react@23.0.0-beta.23'
  - '@nx/rollup@23.0.0-beta.23'
  - '@nx/vite@23.0.0-beta.23'
  - '@nx/vitest@23.0.0-beta.23'
  - '@nx/web@23.0.0-beta.23'
  - '@nx/workspace@23.0.0-beta.23'
  - nx@23.0.0-beta.23
  - '@nx/eslint-plugin@23.0.0-beta.23'
